# Test service providers

# Example OIDC IAL1 app
'urn:gov:gsa:openidconnect.profiles:sp:sso:example_agency:example_oidc_ial1':
  friendly_name: 'Example OIDC IAL1 app'
  agency: 'GSA'
  agency_id: 9
  ial: '1'
  logo: 'generic.svg'
  cert: 'example'
  redirect_uris:
    - 'https://prod.agency.gov/openid'
    - 'https://staging.agency.gov/openid'
  return_to_sp_url: 'https://prod.agency.gov'
  push_notification_url: 'https://prod.agency.gov/notifications'
  help_text:
    en:
      forgot_password: Forgot password help text in English
      sign_in: Sign in help text in English
      sign_up: Sign up help text in English
    es:
      forgot_password: Forgot password help text in Spanish
      sign_in: Sign in help text in Spanish
      sign_up: Sign up help text in Spanish
    fr:
      forgot_password: Forgot password help text in French
      sign_in: Sign in help text in French
      sign_up: Sign up help text in French
  restrict_to_deploy_env: 'prod'

# Example SAML IAL1 app
'urn:gov:gsa:SAML:2.0.profiles:sp:sso:example_agency:example_saml_ial1':
  friendly_name: 'Example SAML IAL1 app'
  agency: 'HHS'
  agency_id: 19
  ial: '1'
  logo: 'generic.svg'
  cert: 'example'
  acs_url: 'https://prod.agency.gov/auth/saml/callback'
  assertion_consumer_logout_service_url: 'https://prod.agency.gov/auth/saml/logout'
  return_to_sp_url: 'https://prod.agency.gov'
  push_notification_url: 'https://prod.agency.gov/notifications'
  help_text:
    en:
      forgot_password: Forgot password help text in English
      sign_in: Sign in help text in English
      sign_up: Sign up help text in English
    es:
      forgot_password: Forgot password help text in Spanish
      sign_in: Sign in help text in Spanish
      sign_up: Sign up help text in Spanish
    fr:
      forgot_password: Forgot password help text in French
      sign_in: Sign in help text in French
      sign_up: Sign up help text in French
  restrict_to_deploy_env: 'prod'

# Example OIDC IAL2 app
'urn:gov:gsa:openidconnect.profiles:sp:sso:example_agency:example_oidc_ial2':
  friendly_name: 'Example OIDC IAL2 app'
  agency: 'DOD'
  agency_id: 8
  ial: '2'
  logo: 'generic.svg'
  cert: 'example'
  redirect_uris:
    - 'https://prod.agency.gov/openid'
    - 'https://staging.agency.gov/openid'
  return_to_sp_url: 'https://prod.agency.gov'
  push_notification_url: 'https://prod.agency.gov/notifications'
  attribute_bundle:
    - email
    - first_name
    - middle_name
    - last_name
    - dob
    - ssn
    - address1
    - address2
    - city
    - state
    - zipcode
    - phone
  help_text:
    en:
      forgot_password: Forgot password help text in English
      sign_in: Sign in help text in English
      sign_up: Sign up help text in English
    es:
      forgot_password: Forgot password help text in Spanish
      sign_in: Sign in help text in Spanish
      sign_up: Sign up help text in Spanish
    fr:
      forgot_password: Forgot password help text in French
      sign_in: Sign in help text in French
      sign_up: Sign up help text in French
  restrict_to_deploy_env: 'prod'

# Example SAML IAL2 app
'urn:gov:gsa:SAML:2.0.profiles:sp:sso:example_agency:example_saml_ial2':
  friendly_name: 'Example SAML IAL2 app'
  agency: 'DOI'
  agency_id: 16
  ial: '2'
  logo: 'generic.svg'
  cert: 'example'
  acs_url: 'https://prod.agency.gov/auth/saml/callback'
  assertion_consumer_logout_service_url: 'https://prod.agency.gov/auth/saml/logout'
  return_to_sp_url: 'https://prod.agency.gov'
  push_notification_url: 'https://prod.agency.gov/notifications'
  attribute_bundle:
    - email
    - first_name
    - middle_name
    - last_name
    - dob
    - ssn
    - address1
    - address2
    - city
    - state
    - zipcode
    - phone
  help_text:
    en:
      forgot_password: Forgot password help text in English
      sign_in: Sign in help text in English
      sign_up: Sign up help text in English
    es:
      forgot_password: Forgot password help text in Spanish
      sign_in: Sign in help text in Spanish
      sign_up: Sign up help text in Spanish
    fr:
      forgot_password: Forgot password help text in French
      sign_in: Sign in help text in French
      sign_up: Sign up help text in French
  restrict_to_deploy_env: 'prod'
